// This file is automatically generated.
// Please do not change this file!
export const file: string;
export const itemHeader: string;
export const itemTitle: string;
export const mappings: string;
export const masterwork: string;
export const names: string;
export const sources: string;
export const sourcesContent: string;
export const subTitle: string;
export const titleContainer: string;
export const version: string;
