// This file is automatically generated.
// Please do not change this file!
export const ammo: string;
export const ammoIcon: string;
export const arcIcon: string;
export const element: string;
export const file: string;
export const heavyAmmo: string;
export const itemHeader: string;
export const itemTitle: string;
export const mappings: string;
export const names: string;
export const powerElement: string;
export const powerInfo: string;
export const primaryAmmo: string;
export const solarIcon: string;
export const sources: string;
export const sourcesContent: string;
export const specialAmmo: string;
export const subSection: string;
export const subTitle: string;
export const titleContainer: string;
export const version: string;
export const voidIcon: string;
